//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

// Code generated by controller-gen. DO NOT EDIT.

// This file was autogenerated by the controller tool, do not edit it manually to ensure your code compiles.
